done
voquanghoa/ClubManagement pull request #55
Opened 2018-08-02 12:17 UTC by nguyenvanman

2018-08-06 16:15 UTC, voquanghoa requested changes
Please change the title of this pull request.

2018-08-06 16:15 UTC, voquanghoa commented on ClubManagement/ClubManagement/Activities/MoneyDetailActivity.cs
> +            tvDescription.Text = $"{time} - Budget : {budget * 1000} đ\n\n{description}";
Why we need to `*1000` here?

2018-08-07 05:31 UTC, nguyenvanman commented on ClubManagement/ClubManagement/Activities/MoneyDetailActivity.cs
> +            tvDescription.Text = $"{time} - Budget : {budget * 1000} đ\n\n{description}";
currency unit is 1000đ

2018-08-07 06:56 UTC, voquanghoa commented on ClubManagement/ClubManagement/Activities/MoneyDetailActivity.cs
> +            tvDescription.Text = $"{time} - Budget : {budget * 1000} đ\n\n{description}";
No, don't do it

2018-08-07 11:42 UTC, closed without merging